name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write # for creating releases
  id-token: write # for trusted publishing to crates.io

jobs:

  ci:
    uses: ./.github/workflows/ci.yaml

  release:
    needs:
      - ci
    uses: scm-rs/shared-workflows/.github/workflows/release.yaml@main
